#FROM registry.access.redhat.com/ubi8/ubi:8.7
ARG BASE_IMAGE
FROM $BASE_IMAGE
RUN yum install -y sudo

RUN useradd -m -d /home/tester -s /bin/bash test_user \
    && echo 'test_user ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/test_user \
    && chmod 440 /etc/sudoers.d/test_user

USER test_user
WORKDIR /home/tester
